### ISSUE TITLE
lidR reverse dependency check

### ISSUE THREAD

**Issue by Jean-Romain** [cran/uavRst#1]
Hi,

`uavRst` (CRAN version) depends (in suggest field) on `lidR`. I planned to release lidR 2.0.0 before to have any dependency but too late... I [searched in the source code](https://github.com/cran/uavRst/search?l=R&q=lidR) to find occurence of lidR. I found only  few occurrences of `readLAS`, `writeLAS` and `lasclipRectangle`. Reading the code it seems ok, your code should still work with the new release. 

I'm also running a revert dependency check but `devtools` changed and the new package `revdepcheck` looks frozen. Revert dependency check is not as before.  Could you confirm that I will not break your current release with the update of lidR.

Cheers

**Edit**: `revdepcheck` finally said *ok* but is still running anyway... Well `devtools` output was more user friendly :disappointed:

**Comment by Jean-Romain** [comment]
Unclear outptut

```
# Platform

|field    |value                        |
|:--------|:----------------------------|
|version  |R version 3.5.1 (2018-07-02) |
|os       |Linux Mint 18.3              |
|system   |x86_64, linux-gnu            |
|ui       |RStudio                      |
|language |(EN)                         |
|collate  |fr_CA.UTF-8                  |
|ctype    |fr_CA.UTF-8                  |
|tz       |America/Toronto              |
|date     |2018-12-21                   |

# Dependencies

|package |old   |new |Δ  |
|:-------|:-----|:---|:--|
|lidR    |1.6.1 |NA  |*  |

# Revdeps

## Couldn't check (1)

|package |version |error |warning |note |
|:-------|:-------|:-----|:-------|:----|
|uavRst  |?       |      |        |     |

## All (1)

|package |version |error |warning |note |
|:-------|:-------|:-----|:-------|:----|
|uavRst  |?       |      |        |     |
```

**Comment by gaborcsardi** [comment]
This is a read-only mirror of CRAN, please see the package authors in the `DESCRIPTION` file.

**Comment by Jean-Romain** [comment]
oups wrong tab in my browser sorry...
